// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyqYf_O4ZeYy9CDB0T6LvOHNWAerpbjg',
    appId: '1:1078834187340:web:a1adca277bf1f86a7df8e9',
    messagingSenderId: '1078834187340',
    projectId: 'book-club-bcb1e',
    authDomain: 'book-club-bcb1e.firebaseapp.com',
    storageBucket: 'book-club-bcb1e.appspot.com',
    measurementId: 'G-80V8140ZVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWgs-gVRgwxay-6Zw18MDWc4CFHugHTGQ',
    appId: '1:1078834187340:android:d9daea8d08ad357a7df8e9',
    messagingSenderId: '1078834187340',
    projectId: 'book-club-bcb1e',
    storageBucket: 'book-club-bcb1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5BYveZduV2sHm1usPsjoBi6r7KktTxM',
    appId: '1:1078834187340:ios:7a0702053997742e7df8e9',
    messagingSenderId: '1078834187340',
    projectId: 'book-club-bcb1e',
    storageBucket: 'book-club-bcb1e.appspot.com',
    iosClientId: '1078834187340-ep31bfkm0fjh8ospf0t6tso7chgbml2k.apps.googleusercontent.com',
    iosBundleId: 'com.verinaEHAB.bookClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd5BYveZduV2sHm1usPsjoBi6r7KktTxM',
    appId: '1:1078834187340:ios:7a0702053997742e7df8e9',
    messagingSenderId: '1078834187340',
    projectId: 'book-club-bcb1e',
    storageBucket: 'book-club-bcb1e.appspot.com',
    iosClientId: '1078834187340-ep31bfkm0fjh8ospf0t6tso7chgbml2k.apps.googleusercontent.com',
    iosBundleId: 'com.verinaEHAB.bookClub',
  );
}
